<?php
    $apiKey = "rzp_test_O0lOFXyfN7a4L0";
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Razorpay Payment</title>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    
    <style>
        /* Style for the Razorpay button */
        /* body{
            margin-top: 300px;
            margin-left: 100px;
        } */
        .razorpay-payment-button {
            background-color: #1d3557; /* Button background color */
            color: white; /* Text color */
            padding: 10px 20px; /* Padding */
            border: none; /* No border */
            border-radius: 15px; /* Rounded corners */
            font-size: 16px; /* Font size */
            cursor: pointer; /* Pointer cursor on hover */
            transition: background-color 0.3s ease; /* Smooth transition for hover effect */
        }
        
        .razorpay-payment-button:hover {
            background-color: #020230; /* Darker shade on hover */
        }
    </style>
</head>
<body>

<form action="success.html" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="100" // Amount is in currency subunits. Hence, 100 refers to 100 paise or ₹1.
        data-currency="INR" // You can accept international payments by changing the currency code.
        data-id="<?php echo 'OID69'; ?>" // Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="Suyash Chatur Pvt. Ltd."
        data-description="Enjoy Your Visit at the Museum"
        data-image="https://iitmjanakpuri-sdc.in/SDC_Team/Photos/suyash.jpeg"
        data-prefill.name="Gaurav Kumar"
        data-prefill.email="gaurav.kumar@example.com"
        data-theme.color="#03045e"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

<script>
$(document).ready(function() {
    // Apply additional styles if needed after the button is rendered
    $('.razorpay-payment-button').css({
        'font-family': 'Arial, sans-serif',
        'text-transform': 'uppercase',
        'box-shadow': '0 2px 4px rgba(0,0,0,0.2)'
    });
});
</script>

</body>
</html>